CREATE USER postgres WITH PASSWORD 'admin';
CREATE DATABASE envios_db OWNER postgres;

\c envios_db

ALTER SCHEMA public OWNER TO postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT CREATE ON SCHEMA public TO postgres;

ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public
GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public
GRANT ALL ON SEQUENCES TO postgres;

ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public
GRANT ALL ON FUNCTIONS TO postgres;