CREATE USER gym_user WITH PASSWORD 'admin';
CREATE DATABASE gym OWNER gym_user;

\c gym

ALTER SCHEMA public OWNER TO gym_user;
GRANT ALL ON SCHEMA public TO gym_user;
GRANT CREATE ON SCHEMA public TO gym_user;

ALTER DEFAULT PRIVILEGES FOR USER gym_user IN SCHEMA public
GRANT ALL ON TABLES TO gym_user;

ALTER DEFAULT PRIVILEGES FOR USER gym_user IN SCHEMA public
GRANT ALL ON SEQUENCES TO gym_user;

ALTER DEFAULT PRIVILEGES FOR USER gym_user IN SCHEMA public
GRANT ALL ON FUNCTIONS TO gym_user;